name: Package and upload to nuget.org

on:
  push:
    branches:
      - main
        
  workflow_dispatch: 
    
jobs:
  package:
    runs-on:
      - ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Gitversion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: 5.x
          
      - name: Determain current version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        
      - name: Pack
        shell: pwsh
        run: |
          dotnet pack `
            ./SagaFlow/SagaFlow.csproj `
            --configuration Release `
            --output .\output\ `
            /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} `
            /p:AssemplyFileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }}
            
      - name: Upload to nuget
        shell: pwsh
        run: |
          dotnet nuget push `
            .\output\*.nuget `
            --source https://api.nuget.org/v3/index.json `
            --api-key ${{ secrets.NUGET_API_KEY }} `
            --skip-duplicate